version: '2'
services:
  mysql:
    image: mysql:latest
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
